const assert=require("assert"),fs=require("fs"),os=require("os"),path=require("path"),cp=require("child_process"),p=require("../bridge/codex-plugin-install.js");
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),"codex plugin install "));

let x=p.buildCodexPluginSpawn("C:\\Program Files\\tool\\codex.cmd",["plugin","marketplace","add","D:\\Project With Space"],"win32","Code.exe","cmd.exe");
assert.strictEqual(x.file,"cmd.exe");assert.strictEqual(x.shell,false);assert.strictEqual(x.windowsVerbatimArguments,true);assert.match(x.args[3],/^""C:\\Program Files/);assert.match(x.args[3],/"D:\\Project With Space""$/);
x=p.buildCodexPluginSpawn("C:\\Program Files\\tool\\codex.bat",["plugin"],"win32","Code.exe","cmd.exe");assert.strictEqual(x.file,"cmd.exe");
x=p.buildCodexPluginSpawn("C:\\tools\\codex.js",["plugin"],"win32","Code.exe","cmd.exe");assert.deepStrictEqual(x,{file:"Code.exe",args:["C:\\tools\\codex.js","plugin"],shell:false,windowsVerbatimArguments:false,env:{ELECTRON_RUN_AS_NODE:"1"}});
x=p.buildCodexPluginSpawn("C:\\tools\\codex.exe",["plugin"],"win32","Code.exe","cmd.exe");assert.deepStrictEqual(x,{file:"C:\\tools\\codex.exe",args:["plugin"],shell:false,windowsVerbatimArguments:false,env:{}});
x=p.buildCodexPluginSpawn("codex",["plugin","marketplace","add","D:\\Project With Space"],"win32","Code.exe","cmd.exe");assert.strictEqual(x.file,"cmd.exe");assert.match(x.args[3],/"D:\\Project With Space"/);assert.match(x.args[3],/^codex /);

if(process.platform==="win32"){
  const cmd=path.join(tmp,"echo args.cmd");fs.writeFileSync(cmd,'@echo off\r\nnode -e "process.stdout.write(JSON.stringify(process.argv.slice(1)))" %*\r\n');
  const plan=p.buildCodexPluginSpawn(cmd,["one","two words",tmp],"win32",process.execPath,process.env.ComSpec),r=cp.spawnSync(plan.file,plan.args,{encoding:"utf8",shell:false,windowsVerbatimArguments:plan.windowsVerbatimArguments,env:{...process.env,...plan.env}});assert.strictEqual(r.status,0,r.stderr);assert.deepStrictEqual(JSON.parse(r.stdout),["one","two words",tmp]);
  fs.writeFileSync(path.join(tmp,"codex"),"invalid-posix-shim");fs.writeFileSync(path.join(tmp,"codex.cmd"),'@echo off\r\nnode -e "process.stdout.write(JSON.stringify(process.argv.slice(1)))" %*\r\n');
  const bare=p.buildCodexPluginSpawn("codex",["two words",tmp],"win32",process.execPath,process.env.ComSpec),br=cp.spawnSync(bare.file,bare.args,{encoding:"utf8",shell:false,windowsVerbatimArguments:bare.windowsVerbatimArguments,env:{...process.env,PATH:tmp+path.delimiter+process.env.PATH}});assert.strictEqual(br.status,0,br.stderr);assert.deepStrictEqual(JSON.parse(br.stdout),["two words",tmp]);
}
const js=path.join(tmp,"launcher.js");fs.writeFileSync(js,'process.stdout.write(JSON.stringify({e:process.env.ELECTRON_RUN_AS_NODE,a:process.argv.slice(2)}));');
const jp=p.buildCodexPluginSpawn(js,["two words"],process.platform,process.execPath,process.env.ComSpec),jr=cp.spawnSync(jp.file,jp.args,{encoding:"utf8",shell:false,env:{...process.env,...jp.env}});assert.strictEqual(jr.status,0,jr.stderr);assert.deepStrictEqual(JSON.parse(jr.stdout),{e:"1",a:["two words"]});

const list=JSON.stringify({marketplaces:[{name:"codex-peek-local",root:"C:\\Repo"}]});assert.strictEqual(p.marketplaceStepOk(0,1,"","codex-peek-local","C:\\Repo","win32"),true);assert.strictEqual(p.marketplaceStepOk(1,0,list,"codex-peek-local","c:\\repo\\","win32"),true);assert.strictEqual(p.marketplaceStepOk(1,0,list,"codex-peek-local","C:\\Other","win32"),false);assert.strictEqual(p.marketplaceStepOk(1,1,"","codex-peek-local","C:\\Repo","win32"),false);
assert.deepStrictEqual(p.codexPeekPluginState(JSON.stringify({installed:[{pluginId:"codex-peek@personal",name:"codex-peek",installed:true,enabled:true}]})),{present:true,enabled:true,pluginId:"codex-peek@personal"});
assert.deepStrictEqual(p.codexPeekPluginState(JSON.stringify({installed:[{pluginId:"codex-peek@personal",name:"codex-peek",installed:true,enabled:false}]})),{present:true,enabled:false,pluginId:"codex-peek@personal"});
assert.deepStrictEqual(p.codexPeekPluginState(JSON.stringify({installed:[{pluginId:"codex-peek@unrelated",name:"codex-peek",installed:true,enabled:true}]})),{present:false,enabled:false,pluginId:""});assert.deepStrictEqual(p.codexPeekPluginState("broken"),{present:false,enabled:false,pluginId:""});

const bridge=path.join(tmp,"bridge"),hookFile=path.join(tmp,"codex-home","hooks.json"),command=p.codexPeekHookCommand("node",bridge);
assert.strictEqual(p.isCodexPeekHookCommand(command,bridge),true,"exact generated command");
assert.strictEqual(p.isCodexPeekHookCommand('"C:/Program Files/nodejs/node.exe" "'+path.join(bridge,"codex-hook.js").replace(/\\/g,"/")+'"',bridge),true,"quoted absolute node executable");
assert.strictEqual(p.isCodexPeekHookCommand('echo "'+path.join(bridge,"codex-hook.js").replace(/\\/g,"/")+'"',bridge),false,"echo mention is not a hook command");
assert.strictEqual(p.isCodexPeekHookCommand(command+" && echo not-the-hook",bridge),false,"shell suffix is rejected");
assert.strictEqual(p.isCodexPeekHookCommand('node evil.js "'+path.join(bridge,"codex-hook.js").replace(/\\/g,"/")+'"',bridge),false,"extra script argument is rejected");
assert.strictEqual(p.isCodexPeekHookCommand('python "'+path.join(bridge,"codex-hook.js").replace(/\\/g,"/")+'"',bridge),false,"non-node executable is rejected");
fs.mkdirSync(path.dirname(hookFile),{recursive:true});fs.writeFileSync(hookFile,JSON.stringify({hooks:{Stop:[{hooks:[{type:"command",command:"node other-stop.js"}]}]}}));
let ir=p.installCodexPeekUserHooks(hookFile,bridge,"node");assert.strictEqual(ir.ok,true);assert.ok(ir.backup&&fs.existsSync(ir.backup));assert.strictEqual(p.detectCodexPeekUserHooks(hookFile,bridge).installed,true);
let installed=JSON.parse(fs.readFileSync(hookFile,"utf8"));assert.strictEqual(installed.hooks.Stop.some(g=>g.hooks.some(h=>h.command==="node other-stop.js")),true);
ir=p.installCodexPeekUserHooks(hookFile,bridge,"node");assert.strictEqual(ir.ok,true);
for(const h of p.CODEX_PEEK_USER_HOOKS){installed=JSON.parse(fs.readFileSync(hookFile,"utf8"));const groups=installed.hooks[h.event];assert.strictEqual(groups.flatMap(g=>g.hooks||[]).filter(v=>p.isCodexPeekHookCommand(v.command,bridge)).length,1,h.event+" remains single");}
let rr=p.removeCodexPeekUserHooks(hookFile,bridge);assert.strictEqual(rr.ok,true);assert.strictEqual(rr.removed,4);assert.strictEqual(p.detectCodexPeekUserHooks(hookFile,bridge).installed,false);assert.strictEqual(JSON.parse(fs.readFileSync(hookFile,"utf8")).hooks.Stop[0].hooks[0].command,"node other-stop.js");
const broken=path.join(tmp,"broken-hooks.json");fs.writeFileSync(broken,"{broken");assert.strictEqual(p.installCodexPeekUserHooks(broken,bridge,"node").ok,false);assert.strictEqual(fs.readFileSync(broken,"utf8"),"{broken");

fs.mkdirSync(bridge,{recursive:true});fs.writeFileSync(path.join(bridge,"codex-hook.js"),"// runtime");
const ownerMarker=path.join(bridge,"codex-hooks-installed-by-extension"),ownedHook=path.join(tmp,"owned-home","hooks.json");
ir=p.installCodexPeekOwnedUserHooks(ownedHook,bridge,"node",ownerMarker);assert.strictEqual(ir.ok,true);let owner=p.readCodexPeekHookOwner(ownerMarker,bridge);assert.strictEqual(owner.ok&&owner.present,true);assert.deepStrictEqual(owner.hookFiles.map(path.normalize),[path.normalize(ownedHook)]);
const ownedHookB=path.join(tmp,"owned-home-b","hooks.json");ir=p.installCodexPeekOwnedUserHooks(ownedHookB,bridge,"node",ownerMarker);assert.strictEqual(ir.ok,true);owner=p.readCodexPeekHookOwner(ownerMarker,bridge);assert.strictEqual(owner.hookFiles.length,2,"home changes append the exact hook file to the ownership ledger");
rr=p.removeCodexPeekOwnedUserHooks(ownerMarker,bridge);assert.strictEqual(rr.ok,true);assert.strictEqual(rr.removed,8);assert.strictEqual(fs.existsSync(ownerMarker),false);assert.strictEqual(p.detectCodexPeekUserHooks(ownedHook,bridge).missing.length,4);assert.strictEqual(p.detectCodexPeekUserHooks(ownedHookB,bridge).missing.length,4);
const rollbackHook=path.join(tmp,"rollback-home","hooks.json"),original=JSON.stringify({other:true});fs.mkdirSync(path.dirname(rollbackHook),{recursive:true});fs.writeFileSync(rollbackHook,original);const blocker=path.join(tmp,"marker-parent-is-file");fs.writeFileSync(blocker,"x");ir=p.installCodexPeekOwnedUserHooks(rollbackHook,bridge,"node",path.join(blocker,"marker"));assert.strictEqual(ir.ok,false);assert.strictEqual(fs.readFileSync(rollbackHook,"utf8"),original,"marker failure restores hooks.json exactly");
const invalidMarker=path.join(tmp,"invalid-owner");fs.writeFileSync(invalidMarker,"timestamp-only");assert.strictEqual(p.readCodexPeekHookOwner(invalidMarker,bridge).ok,false,"legacy/invalid ownership marker fails closed");

const raceRoot=path.join(tmp,"owner-race"),raceBridge=path.join(raceRoot,"bridge"),raceMarker=path.join(raceBridge,"codex-hooks-installed-by-extension"),raceRuntime=path.join(raceBridge,"codex-hook.js"),raceWorker=path.join(raceRoot,"worker.js");fs.mkdirSync(raceBridge,{recursive:true});fs.writeFileSync(raceRuntime,"// runtime");
fs.writeFileSync(raceWorker,`
const fs=require("fs"),p=require(${JSON.stringify(path.join(__dirname,"..","bridge","codex-plugin-install.js"))});
const [mode,bridge,marker,hookFile,ready,release,done]=process.argv.slice(2);
let r;
if(mode==="hold-install")r=p.withCodexPeekHookOwnerLock(bridge,()=>{fs.writeFileSync(ready,"1");while(!fs.existsSync(release))Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,10);return p.installCodexPeekOwnedUserHooksUnlocked(hookFile,bridge,"node",marker);});
else if(mode==="hold-remove")r=p.withCodexPeekHookOwnerLock(bridge,()=>{fs.writeFileSync(ready,"1");while(!fs.existsSync(release))Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,10);const x=p.removeCodexPeekOwnedUserHooksUnlocked(marker,bridge);if(x.ok)try{fs.unlinkSync(require("path").join(bridge,"codex-hook.js"));}catch{}return x;});
else if(mode==="locked-install"){fs.writeFileSync(ready,"attempted");r=p.withCodexPeekHookOwnerLock(bridge,()=>{fs.writeFileSync(release,"entered");return p.installCodexPeekOwnedUserHooksUnlocked(hookFile,bridge,"node",marker);});}
else r=p.installCodexPeekOwnedUserHooks(hookFile,bridge,"node",marker);
fs.writeFileSync(done,JSON.stringify(r));
`);
const waitFile=(f,ms=10000)=>{const end=Date.now()+ms;while(Date.now()<end&&!fs.existsSync(f))Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,10);return fs.existsSync(f);};
const readyA=path.join(raceRoot,"ready-a"),releaseA=path.join(raceRoot,"release-a"),attemptB=path.join(raceRoot,"attempt-b"),enteredB=path.join(raceRoot,"entered-b"),doneA=path.join(raceRoot,"done-a"),doneB=path.join(raceRoot,"done-b"),raceA=path.join(raceRoot,"home-a","hooks.json"),raceB=path.join(raceRoot,"home-b","hooks.json");
assert.match(p.installCodexPeekOwnedUserHooks.toString(),/withCodexPeekHookOwnerLock/,"public installer routes through the owner lock");
cp.spawn(process.execPath,[raceWorker,"hold-install",raceBridge,raceMarker,raceA,readyA,releaseA,doneA],{stdio:"ignore"});assert.strictEqual(waitFile(readyA),true,"first installer owns the process lock");cp.spawn(process.execPath,[raceWorker,"locked-install",raceBridge,raceMarker,raceB,attemptB,enteredB,doneB],{stdio:"ignore"});assert.strictEqual(waitFile(attemptB),true,"second installer reached the lock attempt");Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,120);assert.strictEqual(fs.existsSync(enteredB),false,"second installer cannot enter its RMW callback while A owns the lock");fs.writeFileSync(releaseA,"1");assert.strictEqual(waitFile(enteredB)&&waitFile(doneA)&&waitFile(doneB),true,"B enters only after A completes its protected RMW");assert.strictEqual(JSON.parse(fs.readFileSync(doneA)).ok&&JSON.parse(fs.readFileSync(doneB)).ok,true);owner=p.readCodexPeekHookOwner(raceMarker,raceBridge);assert.strictEqual(owner.hookFiles.length,2,"serialized concurrent A/B installs preserve both owned hook paths");
const readyR=path.join(raceRoot,"ready-r"),releaseR=path.join(raceRoot,"release-r"),doneR=path.join(raceRoot,"done-r"),doneLate=path.join(raceRoot,"done-late"),lateHook=path.join(raceRoot,"home-late","hooks.json");
cp.spawn(process.execPath,[raceWorker,"hold-remove",raceBridge,raceMarker,"-",readyR,releaseR,doneR],{stdio:"ignore"});assert.strictEqual(waitFile(readyR),true,"remover owns the same process lock through runtime deletion");cp.spawn(process.execPath,[raceWorker,"install",raceBridge,raceMarker,lateHook,"-","-",doneLate],{stdio:"ignore"});Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,80);fs.writeFileSync(releaseR,"1");assert.strictEqual(waitFile(doneR)&&waitFile(doneLate),true,"remove/install race finishes");assert.strictEqual(JSON.parse(fs.readFileSync(doneR)).ok,true);assert.strictEqual(JSON.parse(fs.readFileSync(doneLate)).ok,false,"installer serialized after runtime deletion refuses to create a dangling hook");assert.strictEqual(p.detectCodexPeekUserHooks(lateHook,raceBridge).missing.length,4);assert.strictEqual(fs.existsSync(raceMarker),false);

p.installCodexPeekUserHooks(hookFile,bridge,"node");
const hook=(eventName,trustStatus="trusted",enabled=true)=>({source:"user",sourcePath:hookFile,command,eventName,trustStatus,enabled});
let hs=p.codexPeekHookTrustState({data:[{cwd:tmp,hooks:[hook("sessionStart"),hook("userPromptSubmit"),hook("postToolUse"),hook("stop")]}]},hookFile,bridge);assert.strictEqual(hs.ready,true);assert.strictEqual(hs.trusted,4);assert.deepStrictEqual(hs.missingEvents,[]);
hs=p.codexPeekHookTrustState({result:{data:[{cwd:tmp,hooks:[hook("sessionStart"),hook("userPromptSubmit","untrusted"),hook("postToolUse"),hook("stop","modified")]}]}},hookFile,bridge);assert.strictEqual(hs.ready,false);assert.strictEqual(hs.untrusted,2);assert.deepStrictEqual(hs.statuses.sort(),["modified","untrusted"]);
hs=p.codexPeekHookTrustState(JSON.stringify({data:[{cwd:tmp,hooks:[hook("sessionStart"),hook("userPromptSubmit"),hook("postToolUse","trusted",false),{...hook("stop"),sourcePath:path.join(tmp,"other-hooks.json")}]}]}),hookFile,bridge);assert.strictEqual(hs.ready,false);assert.deepStrictEqual(hs.missingEvents.sort(),["postToolUse","stop"]);assert.strictEqual(hs.disabled,1);
const pluginHook=(eventName)=>({source:"plugin",pluginId:"codex-peek@personal",eventName,trustStatus:"trusted",enabled:true,command:'node "%PLUGIN_ROOT%/scripts/codex-hook-launcher.js"'});
hs=p.codexPeekHookTrustState({data:[{cwd:tmp,hooks:[pluginHook("sessionStart"),pluginHook("userPromptSubmit"),pluginHook("postToolUse"),pluginHook("stop")]}]},hookFile,bridge);assert.strictEqual(hs.found,false);assert.strictEqual(hs.ready,false,"plugin-only hooks are not runtime authority");
console.log("codex-plugin-install: user-hook runtime assertions passed");
